/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppBarApprovalsRouteImport } from './routes/_app.bar-approvals'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppFloatRouteImport } from './routes/_app.float'
import { Route as AppHandoverRouteImport } from './routes/_app.handover'
import { Route as AppStockRouteImport } from './routes/_app.stock'
import { Route as AppStoreRouteImport } from './routes/_app.store'
import { Route as AppVarianceThresholdsRouteImport } from './routes/_app.variance-thresholds'
import { Route as AppAdjustmentsIndexRouteImport } from './routes/_app.adjustments.index'
import { Route as AppAdjustmentsIdRouteImport } from './routes/_app.adjustments.$id'
import { Route as AppAuditIndexRouteImport } from './routes/_app.audit.index'
import { Route as AppAuditIdRouteImport } from './routes/_app.audit.$id'
import { Route as AppBarIndexRouteImport } from './routes/_app.bar.index'
import { Route as AppBarHandoverRouteImport } from './routes/_app.bar.handover'
import { Route as AppBarOrdersRouteImport } from './routes/_app.bar.orders'
import { Route as AppBarReportsRouteImport } from './routes/_app.bar.reports'
import { Route as AppBarStockRouteImport } from './routes/_app.bar.stock'
import { Route as AppBillsIndexRouteImport } from './routes/_app.bills.index'
import { Route as AppBillsIdRouteImport } from './routes/_app.bills.$id'
import { Route as AppCashDropsIndexRouteImport } from './routes/_app.cash-drops.index'
import { Route as AppCashDropsIdRouteImport } from './routes/_app.cash-drops.$id'
import { Route as AppDisputesIndexRouteImport } from './routes/_app.disputes.index'
import { Route as AppDisputesIdRouteImport } from './routes/_app.disputes.$id'
import { Route as AppExceptionsIndexRouteImport } from './routes/_app.exceptions.index'
import { Route as AppExceptionsIdRouteImport } from './routes/_app.exceptions.$id'
import { Route as AppMenuIndexRouteImport } from './routes/_app.menu.index'
import { Route as AppMenuMasterItemsRouteImport } from './routes/_app.menu.master-items'
import { Route as AppOrdersIndexRouteImport } from './routes/_app.orders.index'
import { Route as AppOrdersIdRouteImport } from './routes/_app.orders.$id'
import { Route as AppOrdersNewRouteImport } from './routes/_app.orders.new'
import { Route as AppPaymentsIndexRouteImport } from './routes/_app.payments.index'
import { Route as AppPaymentsIdRouteImport } from './routes/_app.payments.$id'
import { Route as AppPaymentsPendingRouteImport } from './routes/_app.payments.pending'
import { Route as AppPortionDefinitionsIndexRouteImport } from './routes/_app.portion-definitions.index'
import { Route as AppProductionIndexRouteImport } from './routes/_app.production.index'
import { Route as AppProductionIdRouteImport } from './routes/_app.production.$id'
import { Route as AppProductionVariancesRouteImport } from './routes/_app.production.variances'
import { Route as AppPropertiesIndexRouteImport } from './routes/_app.properties.index'
import { Route as AppRecipesIndexRouteImport } from './routes/_app.recipes.index'
import { Route as AppReconciliationIndexRouteImport } from './routes/_app.reconciliation.index'
import { Route as AppReconciliationIdRouteImport } from './routes/_app.reconciliation.$id'
import { Route as AppReportsIndexRouteImport } from './routes/_app.reports.index'
import { Route as AppReturnsIndexRouteImport } from './routes/_app.returns.index'
import { Route as AppReturnsIdRouteImport } from './routes/_app.returns.$id'
import { Route as AppStaffMealsIndexRouteImport } from './routes/_app.staff-meals.index'
import { Route as AppStaffMealsIdRouteImport } from './routes/_app.staff-meals.$id'
import { Route as AppStaffMealsDailyRouteImport } from './routes/_app.staff-meals.daily'
import { Route as AppStaffMenuIndexRouteImport } from './routes/_app.staff-menu.index'
import { Route as AppStaffMenuWeekStartRouteImport } from './routes/_app.staff-menu.$weekStart'
import { Route as AppStaffMenuStandingRouteImport } from './routes/_app.staff-menu.standing'
import { Route as AppStockBalanceRouteImport } from './routes/_app.stock.balance'
import { Route as AppStockBatchesRouteImport } from './routes/_app.stock.batches'
import { Route as AppStockBulkIssuesRouteImport } from './routes/_app.stock.bulk-issues'
import { Route as AppStockItemsRouteImport } from './routes/_app.stock.items'
import { Route as AppStockLedgerRouteImport } from './routes/_app.stock.ledger'
import { Route as AppStockPortionRouteImport } from './routes/_app.stock.portion'
import { Route as AppStockPortionInventoryRouteImport } from './routes/_app.stock.portion-inventory'
import { Route as AppStoreQueueRouteImport } from './routes/_app.store.queue'
import { Route as AppStoreSlipsRouteImport } from './routes/_app.store.slips'
import { Route as AppTransfersIndexRouteImport } from './routes/_app.transfers.index'
import { Route as AppTransfersIdRouteImport } from './routes/_app.transfers.$id'
import { Route as AppUsersIndexRouteImport } from './routes/_app.users.index'
import { Route as AppWasteIndexRouteImport } from './routes/_app.waste.index'
import { Route as AppWasteIdRouteImport } from './routes/_app.waste.$id'
import { Route as PrintBillIdRouteImport } from './routes/_print.bill.$id'
import { Route as PrintSlipIdRouteImport } from './routes/_print.slip.$id'
import { Route as AppStockBatchesIndexRouteImport } from './routes/_app.stock.batches.index'
import { Route as AppStockBatchesIdRouteImport } from './routes/_app.stock.batches.$id'
import { Route as AppStoreDispatchOrderIdRouteImport } from './routes/_app.store.dispatch.$orderId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppBarApprovalsRoute = AppBarApprovalsRouteImport.update({
  id: '/bar-approvals',
  path: '/bar-approvals',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppFloatRoute = AppFloatRouteImport.update({
  id: '/float',
  path: '/float',
  getParentRoute: () => AppRoute,
} as any)
const AppHandoverRoute = AppHandoverRouteImport.update({
  id: '/handover',
  path: '/handover',
  getParentRoute: () => AppRoute,
} as any)
const AppStockRoute = AppStockRouteImport.update({
  id: '/stock',
  path: '/stock',
  getParentRoute: () => AppRoute,
} as any)
const AppStoreRoute = AppStoreRouteImport.update({
  id: '/store',
  path: '/store',
  getParentRoute: () => AppRoute,
} as any)
const AppVarianceThresholdsRoute = AppVarianceThresholdsRouteImport.update({
  id: '/variance-thresholds',
  path: '/variance-thresholds',
  getParentRoute: () => AppRoute,
} as any)
const AppAdjustmentsIndexRoute = AppAdjustmentsIndexRouteImport.update({
  id: '/adjustments/',
  path: '/adjustments/',
  getParentRoute: () => AppRoute,
} as any)
const AppAdjustmentsIdRoute = AppAdjustmentsIdRouteImport.update({
  id: '/adjustments/$id',
  path: '/adjustments/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppAuditIndexRoute = AppAuditIndexRouteImport.update({
  id: '/audit/',
  path: '/audit/',
  getParentRoute: () => AppRoute,
} as any)
const AppAuditIdRoute = AppAuditIdRouteImport.update({
  id: '/audit/$id',
  path: '/audit/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppBarIndexRoute = AppBarIndexRouteImport.update({
  id: '/bar/',
  path: '/bar/',
  getParentRoute: () => AppRoute,
} as any)
const AppBarHandoverRoute = AppBarHandoverRouteImport.update({
  id: '/bar/handover',
  path: '/bar/handover',
  getParentRoute: () => AppRoute,
} as any)
const AppBarOrdersRoute = AppBarOrdersRouteImport.update({
  id: '/bar/orders',
  path: '/bar/orders',
  getParentRoute: () => AppRoute,
} as any)
const AppBarReportsRoute = AppBarReportsRouteImport.update({
  id: '/bar/reports',
  path: '/bar/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppBarStockRoute = AppBarStockRouteImport.update({
  id: '/bar/stock',
  path: '/bar/stock',
  getParentRoute: () => AppRoute,
} as any)
const AppBillsIndexRoute = AppBillsIndexRouteImport.update({
  id: '/bills/',
  path: '/bills/',
  getParentRoute: () => AppRoute,
} as any)
const AppBillsIdRoute = AppBillsIdRouteImport.update({
  id: '/bills/$id',
  path: '/bills/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppCashDropsIndexRoute = AppCashDropsIndexRouteImport.update({
  id: '/cash-drops/',
  path: '/cash-drops/',
  getParentRoute: () => AppRoute,
} as any)
const AppCashDropsIdRoute = AppCashDropsIdRouteImport.update({
  id: '/cash-drops/$id',
  path: '/cash-drops/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppDisputesIndexRoute = AppDisputesIndexRouteImport.update({
  id: '/disputes/',
  path: '/disputes/',
  getParentRoute: () => AppRoute,
} as any)
const AppDisputesIdRoute = AppDisputesIdRouteImport.update({
  id: '/disputes/$id',
  path: '/disputes/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppExceptionsIndexRoute = AppExceptionsIndexRouteImport.update({
  id: '/exceptions/',
  path: '/exceptions/',
  getParentRoute: () => AppRoute,
} as any)
const AppExceptionsIdRoute = AppExceptionsIdRouteImport.update({
  id: '/exceptions/$id',
  path: '/exceptions/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppMenuIndexRoute = AppMenuIndexRouteImport.update({
  id: '/menu/',
  path: '/menu/',
  getParentRoute: () => AppRoute,
} as any)
const AppMenuMasterItemsRoute = AppMenuMasterItemsRouteImport.update({
  id: '/menu/master-items',
  path: '/menu/master-items',
  getParentRoute: () => AppRoute,
} as any)
const AppOrdersIndexRoute = AppOrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => AppRoute,
} as any)
const AppOrdersIdRoute = AppOrdersIdRouteImport.update({
  id: '/orders/$id',
  path: '/orders/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppOrdersNewRoute = AppOrdersNewRouteImport.update({
  id: '/orders/new',
  path: '/orders/new',
  getParentRoute: () => AppRoute,
} as any)
const AppPaymentsIndexRoute = AppPaymentsIndexRouteImport.update({
  id: '/payments/',
  path: '/payments/',
  getParentRoute: () => AppRoute,
} as any)
const AppPaymentsIdRoute = AppPaymentsIdRouteImport.update({
  id: '/payments/$id',
  path: '/payments/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppPaymentsPendingRoute = AppPaymentsPendingRouteImport.update({
  id: '/payments/pending',
  path: '/payments/pending',
  getParentRoute: () => AppRoute,
} as any)
const AppPortionDefinitionsIndexRoute =
  AppPortionDefinitionsIndexRouteImport.update({
    id: '/portion-definitions/',
    path: '/portion-definitions/',
    getParentRoute: () => AppRoute,
  } as any)
const AppProductionIndexRoute = AppProductionIndexRouteImport.update({
  id: '/production/',
  path: '/production/',
  getParentRoute: () => AppRoute,
} as any)
const AppProductionIdRoute = AppProductionIdRouteImport.update({
  id: '/production/$id',
  path: '/production/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppProductionVariancesRoute = AppProductionVariancesRouteImport.update({
  id: '/production/variances',
  path: '/production/variances',
  getParentRoute: () => AppRoute,
} as any)
const AppPropertiesIndexRoute = AppPropertiesIndexRouteImport.update({
  id: '/properties/',
  path: '/properties/',
  getParentRoute: () => AppRoute,
} as any)
const AppRecipesIndexRoute = AppRecipesIndexRouteImport.update({
  id: '/recipes/',
  path: '/recipes/',
  getParentRoute: () => AppRoute,
} as any)
const AppReconciliationIndexRoute = AppReconciliationIndexRouteImport.update({
  id: '/reconciliation/',
  path: '/reconciliation/',
  getParentRoute: () => AppRoute,
} as any)
const AppReconciliationIdRoute = AppReconciliationIdRouteImport.update({
  id: '/reconciliation/$id',
  path: '/reconciliation/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsIndexRoute = AppReportsIndexRouteImport.update({
  id: '/reports/',
  path: '/reports/',
  getParentRoute: () => AppRoute,
} as any)
const AppReturnsIndexRoute = AppReturnsIndexRouteImport.update({
  id: '/returns/',
  path: '/returns/',
  getParentRoute: () => AppRoute,
} as any)
const AppReturnsIdRoute = AppReturnsIdRouteImport.update({
  id: '/returns/$id',
  path: '/returns/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppStaffMealsIndexRoute = AppStaffMealsIndexRouteImport.update({
  id: '/staff-meals/',
  path: '/staff-meals/',
  getParentRoute: () => AppRoute,
} as any)
const AppStaffMealsIdRoute = AppStaffMealsIdRouteImport.update({
  id: '/staff-meals/$id',
  path: '/staff-meals/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppStaffMealsDailyRoute = AppStaffMealsDailyRouteImport.update({
  id: '/staff-meals/daily',
  path: '/staff-meals/daily',
  getParentRoute: () => AppRoute,
} as any)
const AppStaffMenuIndexRoute = AppStaffMenuIndexRouteImport.update({
  id: '/staff-menu/',
  path: '/staff-menu/',
  getParentRoute: () => AppRoute,
} as any)
const AppStaffMenuWeekStartRoute = AppStaffMenuWeekStartRouteImport.update({
  id: '/staff-menu/$weekStart',
  path: '/staff-menu/$weekStart',
  getParentRoute: () => AppRoute,
} as any)
const AppStaffMenuStandingRoute = AppStaffMenuStandingRouteImport.update({
  id: '/staff-menu/standing',
  path: '/staff-menu/standing',
  getParentRoute: () => AppRoute,
} as any)
const AppStockBalanceRoute = AppStockBalanceRouteImport.update({
  id: '/balance',
  path: '/balance',
  getParentRoute: () => AppStockRoute,
} as any)
const AppStockBatchesRoute = AppStockBatchesRouteImport.update({
  id: '/batches',
  path: '/batches',
  getParentRoute: () => AppStockRoute,
} as any)
const AppStockBulkIssuesRoute = AppStockBulkIssuesRouteImport.update({
  id: '/bulk-issues',
  path: '/bulk-issues',
  getParentRoute: () => AppStockRoute,
} as any)
const AppStockItemsRoute = AppStockItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => AppStockRoute,
} as any)
const AppStockLedgerRoute = AppStockLedgerRouteImport.update({
  id: '/ledger',
  path: '/ledger',
  getParentRoute: () => AppStockRoute,
} as any)
const AppStockPortionRoute = AppStockPortionRouteImport.update({
  id: '/portion',
  path: '/portion',
  getParentRoute: () => AppStockRoute,
} as any)
const AppStockPortionInventoryRoute =
  AppStockPortionInventoryRouteImport.update({
    id: '/portion-inventory',
    path: '/portion-inventory',
    getParentRoute: () => AppStockRoute,
  } as any)
const AppStoreQueueRoute = AppStoreQueueRouteImport.update({
  id: '/queue',
  path: '/queue',
  getParentRoute: () => AppStoreRoute,
} as any)
const AppStoreSlipsRoute = AppStoreSlipsRouteImport.update({
  id: '/slips',
  path: '/slips',
  getParentRoute: () => AppStoreRoute,
} as any)
const AppTransfersIndexRoute = AppTransfersIndexRouteImport.update({
  id: '/transfers/',
  path: '/transfers/',
  getParentRoute: () => AppRoute,
} as any)
const AppTransfersIdRoute = AppTransfersIdRouteImport.update({
  id: '/transfers/$id',
  path: '/transfers/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppUsersIndexRoute = AppUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AppRoute,
} as any)
const AppWasteIndexRoute = AppWasteIndexRouteImport.update({
  id: '/waste/',
  path: '/waste/',
  getParentRoute: () => AppRoute,
} as any)
const AppWasteIdRoute = AppWasteIdRouteImport.update({
  id: '/waste/$id',
  path: '/waste/$id',
  getParentRoute: () => AppRoute,
} as any)
const PrintBillIdRoute = PrintBillIdRouteImport.update({
  id: '/_print/bill/$id',
  path: '/bill/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PrintSlipIdRoute = PrintSlipIdRouteImport.update({
  id: '/_print/slip/$id',
  path: '/slip/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AppStockBatchesIndexRoute = AppStockBatchesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppStockBatchesRoute,
} as any)
const AppStockBatchesIdRoute = AppStockBatchesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppStockBatchesRoute,
} as any)
const AppStoreDispatchOrderIdRoute = AppStoreDispatchOrderIdRouteImport.update({
  id: '/dispatch/$orderId',
  path: '/dispatch/$orderId',
  getParentRoute: () => AppStoreRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/bar-approvals': typeof AppBarApprovalsRoute
  '/dashboard': typeof AppDashboardRoute
  '/float': typeof AppFloatRoute
  '/handover': typeof AppHandoverRoute
  '/stock': typeof AppStockRouteWithChildren
  '/store': typeof AppStoreRouteWithChildren
  '/variance-thresholds': typeof AppVarianceThresholdsRoute
  '/adjustments/$id': typeof AppAdjustmentsIdRoute
  '/audit/$id': typeof AppAuditIdRoute
  '/bar/handover': typeof AppBarHandoverRoute
  '/bar/orders': typeof AppBarOrdersRoute
  '/bar/reports': typeof AppBarReportsRoute
  '/bar/stock': typeof AppBarStockRoute
  '/bills/$id': typeof AppBillsIdRoute
  '/cash-drops/$id': typeof AppCashDropsIdRoute
  '/disputes/$id': typeof AppDisputesIdRoute
  '/exceptions/$id': typeof AppExceptionsIdRoute
  '/menu/master-items': typeof AppMenuMasterItemsRoute
  '/orders/$id': typeof AppOrdersIdRoute
  '/orders/new': typeof AppOrdersNewRoute
  '/payments/$id': typeof AppPaymentsIdRoute
  '/payments/pending': typeof AppPaymentsPendingRoute
  '/production/$id': typeof AppProductionIdRoute
  '/production/variances': typeof AppProductionVariancesRoute
  '/reconciliation/$id': typeof AppReconciliationIdRoute
  '/returns/$id': typeof AppReturnsIdRoute
  '/staff-meals/$id': typeof AppStaffMealsIdRoute
  '/staff-meals/daily': typeof AppStaffMealsDailyRoute
  '/staff-menu/$weekStart': typeof AppStaffMenuWeekStartRoute
  '/staff-menu/standing': typeof AppStaffMenuStandingRoute
  '/stock/balance': typeof AppStockBalanceRoute
  '/stock/batches': typeof AppStockBatchesRouteWithChildren
  '/stock/bulk-issues': typeof AppStockBulkIssuesRoute
  '/stock/items': typeof AppStockItemsRoute
  '/stock/ledger': typeof AppStockLedgerRoute
  '/stock/portion': typeof AppStockPortionRoute
  '/stock/portion-inventory': typeof AppStockPortionInventoryRoute
  '/store/queue': typeof AppStoreQueueRoute
  '/store/slips': typeof AppStoreSlipsRoute
  '/transfers/$id': typeof AppTransfersIdRoute
  '/waste/$id': typeof AppWasteIdRoute
  '/bill/$id': typeof PrintBillIdRoute
  '/slip/$id': typeof PrintSlipIdRoute
  '/adjustments/': typeof AppAdjustmentsIndexRoute
  '/audit/': typeof AppAuditIndexRoute
  '/bar/': typeof AppBarIndexRoute
  '/bills/': typeof AppBillsIndexRoute
  '/cash-drops/': typeof AppCashDropsIndexRoute
  '/disputes/': typeof AppDisputesIndexRoute
  '/exceptions/': typeof AppExceptionsIndexRoute
  '/menu/': typeof AppMenuIndexRoute
  '/orders/': typeof AppOrdersIndexRoute
  '/payments/': typeof AppPaymentsIndexRoute
  '/portion-definitions/': typeof AppPortionDefinitionsIndexRoute
  '/production/': typeof AppProductionIndexRoute
  '/properties/': typeof AppPropertiesIndexRoute
  '/recipes/': typeof AppRecipesIndexRoute
  '/reconciliation/': typeof AppReconciliationIndexRoute
  '/reports/': typeof AppReportsIndexRoute
  '/returns/': typeof AppReturnsIndexRoute
  '/staff-meals/': typeof AppStaffMealsIndexRoute
  '/staff-menu/': typeof AppStaffMenuIndexRoute
  '/transfers/': typeof AppTransfersIndexRoute
  '/users/': typeof AppUsersIndexRoute
  '/waste/': typeof AppWasteIndexRoute
  '/stock/batches/$id': typeof AppStockBatchesIdRoute
  '/store/dispatch/$orderId': typeof AppStoreDispatchOrderIdRoute
  '/stock/batches/': typeof AppStockBatchesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/bar-approvals': typeof AppBarApprovalsRoute
  '/dashboard': typeof AppDashboardRoute
  '/float': typeof AppFloatRoute
  '/handover': typeof AppHandoverRoute
  '/stock': typeof AppStockRouteWithChildren
  '/store': typeof AppStoreRouteWithChildren
  '/variance-thresholds': typeof AppVarianceThresholdsRoute
  '/adjustments/$id': typeof AppAdjustmentsIdRoute
  '/audit/$id': typeof AppAuditIdRoute
  '/bar/handover': typeof AppBarHandoverRoute
  '/bar/orders': typeof AppBarOrdersRoute
  '/bar/reports': typeof AppBarReportsRoute
  '/bar/stock': typeof AppBarStockRoute
  '/bills/$id': typeof AppBillsIdRoute
  '/cash-drops/$id': typeof AppCashDropsIdRoute
  '/disputes/$id': typeof AppDisputesIdRoute
  '/exceptions/$id': typeof AppExceptionsIdRoute
  '/menu/master-items': typeof AppMenuMasterItemsRoute
  '/orders/$id': typeof AppOrdersIdRoute
  '/orders/new': typeof AppOrdersNewRoute
  '/payments/$id': typeof AppPaymentsIdRoute
  '/payments/pending': typeof AppPaymentsPendingRoute
  '/production/$id': typeof AppProductionIdRoute
  '/production/variances': typeof AppProductionVariancesRoute
  '/reconciliation/$id': typeof AppReconciliationIdRoute
  '/returns/$id': typeof AppReturnsIdRoute
  '/staff-meals/$id': typeof AppStaffMealsIdRoute
  '/staff-meals/daily': typeof AppStaffMealsDailyRoute
  '/staff-menu/$weekStart': typeof AppStaffMenuWeekStartRoute
  '/staff-menu/standing': typeof AppStaffMenuStandingRoute
  '/stock/balance': typeof AppStockBalanceRoute
  '/stock/bulk-issues': typeof AppStockBulkIssuesRoute
  '/stock/items': typeof AppStockItemsRoute
  '/stock/ledger': typeof AppStockLedgerRoute
  '/stock/portion': typeof AppStockPortionRoute
  '/stock/portion-inventory': typeof AppStockPortionInventoryRoute
  '/store/queue': typeof AppStoreQueueRoute
  '/store/slips': typeof AppStoreSlipsRoute
  '/transfers/$id': typeof AppTransfersIdRoute
  '/waste/$id': typeof AppWasteIdRoute
  '/bill/$id': typeof PrintBillIdRoute
  '/slip/$id': typeof PrintSlipIdRoute
  '/adjustments': typeof AppAdjustmentsIndexRoute
  '/audit': typeof AppAuditIndexRoute
  '/bar': typeof AppBarIndexRoute
  '/bills': typeof AppBillsIndexRoute
  '/cash-drops': typeof AppCashDropsIndexRoute
  '/disputes': typeof AppDisputesIndexRoute
  '/exceptions': typeof AppExceptionsIndexRoute
  '/menu': typeof AppMenuIndexRoute
  '/orders': typeof AppOrdersIndexRoute
  '/payments': typeof AppPaymentsIndexRoute
  '/portion-definitions': typeof AppPortionDefinitionsIndexRoute
  '/production': typeof AppProductionIndexRoute
  '/properties': typeof AppPropertiesIndexRoute
  '/recipes': typeof AppRecipesIndexRoute
  '/reconciliation': typeof AppReconciliationIndexRoute
  '/reports': typeof AppReportsIndexRoute
  '/returns': typeof AppReturnsIndexRoute
  '/staff-meals': typeof AppStaffMealsIndexRoute
  '/staff-menu': typeof AppStaffMenuIndexRoute
  '/transfers': typeof AppTransfersIndexRoute
  '/users': typeof AppUsersIndexRoute
  '/waste': typeof AppWasteIndexRoute
  '/stock/batches/$id': typeof AppStockBatchesIdRoute
  '/store/dispatch/$orderId': typeof AppStoreDispatchOrderIdRoute
  '/stock/batches': typeof AppStockBatchesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/bar-approvals': typeof AppBarApprovalsRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/float': typeof AppFloatRoute
  '/_app/handover': typeof AppHandoverRoute
  '/_app/stock': typeof AppStockRouteWithChildren
  '/_app/store': typeof AppStoreRouteWithChildren
  '/_app/variance-thresholds': typeof AppVarianceThresholdsRoute
  '/_app/adjustments/$id': typeof AppAdjustmentsIdRoute
  '/_app/audit/$id': typeof AppAuditIdRoute
  '/_app/bar/handover': typeof AppBarHandoverRoute
  '/_app/bar/orders': typeof AppBarOrdersRoute
  '/_app/bar/reports': typeof AppBarReportsRoute
  '/_app/bar/stock': typeof AppBarStockRoute
  '/_app/bills/$id': typeof AppBillsIdRoute
  '/_app/cash-drops/$id': typeof AppCashDropsIdRoute
  '/_app/disputes/$id': typeof AppDisputesIdRoute
  '/_app/exceptions/$id': typeof AppExceptionsIdRoute
  '/_app/menu/master-items': typeof AppMenuMasterItemsRoute
  '/_app/orders/$id': typeof AppOrdersIdRoute
  '/_app/orders/new': typeof AppOrdersNewRoute
  '/_app/payments/$id': typeof AppPaymentsIdRoute
  '/_app/payments/pending': typeof AppPaymentsPendingRoute
  '/_app/production/$id': typeof AppProductionIdRoute
  '/_app/production/variances': typeof AppProductionVariancesRoute
  '/_app/reconciliation/$id': typeof AppReconciliationIdRoute
  '/_app/returns/$id': typeof AppReturnsIdRoute
  '/_app/staff-meals/$id': typeof AppStaffMealsIdRoute
  '/_app/staff-meals/daily': typeof AppStaffMealsDailyRoute
  '/_app/staff-menu/$weekStart': typeof AppStaffMenuWeekStartRoute
  '/_app/staff-menu/standing': typeof AppStaffMenuStandingRoute
  '/_app/stock/balance': typeof AppStockBalanceRoute
  '/_app/stock/batches': typeof AppStockBatchesRouteWithChildren
  '/_app/stock/bulk-issues': typeof AppStockBulkIssuesRoute
  '/_app/stock/items': typeof AppStockItemsRoute
  '/_app/stock/ledger': typeof AppStockLedgerRoute
  '/_app/stock/portion': typeof AppStockPortionRoute
  '/_app/stock/portion-inventory': typeof AppStockPortionInventoryRoute
  '/_app/store/queue': typeof AppStoreQueueRoute
  '/_app/store/slips': typeof AppStoreSlipsRoute
  '/_app/transfers/$id': typeof AppTransfersIdRoute
  '/_app/waste/$id': typeof AppWasteIdRoute
  '/_print/bill/$id': typeof PrintBillIdRoute
  '/_print/slip/$id': typeof PrintSlipIdRoute
  '/_app/adjustments/': typeof AppAdjustmentsIndexRoute
  '/_app/audit/': typeof AppAuditIndexRoute
  '/_app/bar/': typeof AppBarIndexRoute
  '/_app/bills/': typeof AppBillsIndexRoute
  '/_app/cash-drops/': typeof AppCashDropsIndexRoute
  '/_app/disputes/': typeof AppDisputesIndexRoute
  '/_app/exceptions/': typeof AppExceptionsIndexRoute
  '/_app/menu/': typeof AppMenuIndexRoute
  '/_app/orders/': typeof AppOrdersIndexRoute
  '/_app/payments/': typeof AppPaymentsIndexRoute
  '/_app/portion-definitions/': typeof AppPortionDefinitionsIndexRoute
  '/_app/production/': typeof AppProductionIndexRoute
  '/_app/properties/': typeof AppPropertiesIndexRoute
  '/_app/recipes/': typeof AppRecipesIndexRoute
  '/_app/reconciliation/': typeof AppReconciliationIndexRoute
  '/_app/reports/': typeof AppReportsIndexRoute
  '/_app/returns/': typeof AppReturnsIndexRoute
  '/_app/staff-meals/': typeof AppStaffMealsIndexRoute
  '/_app/staff-menu/': typeof AppStaffMenuIndexRoute
  '/_app/transfers/': typeof AppTransfersIndexRoute
  '/_app/users/': typeof AppUsersIndexRoute
  '/_app/waste/': typeof AppWasteIndexRoute
  '/_app/stock/batches/$id': typeof AppStockBatchesIdRoute
  '/_app/store/dispatch/$orderId': typeof AppStoreDispatchOrderIdRoute
  '/_app/stock/batches/': typeof AppStockBatchesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/bar-approvals'
    | '/dashboard'
    | '/float'
    | '/handover'
    | '/stock'
    | '/store'
    | '/variance-thresholds'
    | '/adjustments/$id'
    | '/audit/$id'
    | '/bar/handover'
    | '/bar/orders'
    | '/bar/reports'
    | '/bar/stock'
    | '/bills/$id'
    | '/cash-drops/$id'
    | '/disputes/$id'
    | '/exceptions/$id'
    | '/menu/master-items'
    | '/orders/$id'
    | '/orders/new'
    | '/payments/$id'
    | '/payments/pending'
    | '/production/$id'
    | '/production/variances'
    | '/reconciliation/$id'
    | '/returns/$id'
    | '/staff-meals/$id'
    | '/staff-meals/daily'
    | '/staff-menu/$weekStart'
    | '/staff-menu/standing'
    | '/stock/balance'
    | '/stock/batches'
    | '/stock/bulk-issues'
    | '/stock/items'
    | '/stock/ledger'
    | '/stock/portion'
    | '/stock/portion-inventory'
    | '/store/queue'
    | '/store/slips'
    | '/transfers/$id'
    | '/waste/$id'
    | '/bill/$id'
    | '/slip/$id'
    | '/adjustments/'
    | '/audit/'
    | '/bar/'
    | '/bills/'
    | '/cash-drops/'
    | '/disputes/'
    | '/exceptions/'
    | '/menu/'
    | '/orders/'
    | '/payments/'
    | '/portion-definitions/'
    | '/production/'
    | '/properties/'
    | '/recipes/'
    | '/reconciliation/'
    | '/reports/'
    | '/returns/'
    | '/staff-meals/'
    | '/staff-menu/'
    | '/transfers/'
    | '/users/'
    | '/waste/'
    | '/stock/batches/$id'
    | '/store/dispatch/$orderId'
    | '/stock/batches/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/bar-approvals'
    | '/dashboard'
    | '/float'
    | '/handover'
    | '/stock'
    | '/store'
    | '/variance-thresholds'
    | '/adjustments/$id'
    | '/audit/$id'
    | '/bar/handover'
    | '/bar/orders'
    | '/bar/reports'
    | '/bar/stock'
    | '/bills/$id'
    | '/cash-drops/$id'
    | '/disputes/$id'
    | '/exceptions/$id'
    | '/menu/master-items'
    | '/orders/$id'
    | '/orders/new'
    | '/payments/$id'
    | '/payments/pending'
    | '/production/$id'
    | '/production/variances'
    | '/reconciliation/$id'
    | '/returns/$id'
    | '/staff-meals/$id'
    | '/staff-meals/daily'
    | '/staff-menu/$weekStart'
    | '/staff-menu/standing'
    | '/stock/balance'
    | '/stock/bulk-issues'
    | '/stock/items'
    | '/stock/ledger'
    | '/stock/portion'
    | '/stock/portion-inventory'
    | '/store/queue'
    | '/store/slips'
    | '/transfers/$id'
    | '/waste/$id'
    | '/bill/$id'
    | '/slip/$id'
    | '/adjustments'
    | '/audit'
    | '/bar'
    | '/bills'
    | '/cash-drops'
    | '/disputes'
    | '/exceptions'
    | '/menu'
    | '/orders'
    | '/payments'
    | '/portion-definitions'
    | '/production'
    | '/properties'
    | '/recipes'
    | '/reconciliation'
    | '/reports'
    | '/returns'
    | '/staff-meals'
    | '/staff-menu'
    | '/transfers'
    | '/users'
    | '/waste'
    | '/stock/batches/$id'
    | '/store/dispatch/$orderId'
    | '/stock/batches'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/bar-approvals'
    | '/_app/dashboard'
    | '/_app/float'
    | '/_app/handover'
    | '/_app/stock'
    | '/_app/store'
    | '/_app/variance-thresholds'
    | '/_app/adjustments/$id'
    | '/_app/audit/$id'
    | '/_app/bar/handover'
    | '/_app/bar/orders'
    | '/_app/bar/reports'
    | '/_app/bar/stock'
    | '/_app/bills/$id'
    | '/_app/cash-drops/$id'
    | '/_app/disputes/$id'
    | '/_app/exceptions/$id'
    | '/_app/menu/master-items'
    | '/_app/orders/$id'
    | '/_app/orders/new'
    | '/_app/payments/$id'
    | '/_app/payments/pending'
    | '/_app/production/$id'
    | '/_app/production/variances'
    | '/_app/reconciliation/$id'
    | '/_app/returns/$id'
    | '/_app/staff-meals/$id'
    | '/_app/staff-meals/daily'
    | '/_app/staff-menu/$weekStart'
    | '/_app/staff-menu/standing'
    | '/_app/stock/balance'
    | '/_app/stock/batches'
    | '/_app/stock/bulk-issues'
    | '/_app/stock/items'
    | '/_app/stock/ledger'
    | '/_app/stock/portion'
    | '/_app/stock/portion-inventory'
    | '/_app/store/queue'
    | '/_app/store/slips'
    | '/_app/transfers/$id'
    | '/_app/waste/$id'
    | '/_print/bill/$id'
    | '/_print/slip/$id'
    | '/_app/adjustments/'
    | '/_app/audit/'
    | '/_app/bar/'
    | '/_app/bills/'
    | '/_app/cash-drops/'
    | '/_app/disputes/'
    | '/_app/exceptions/'
    | '/_app/menu/'
    | '/_app/orders/'
    | '/_app/payments/'
    | '/_app/portion-definitions/'
    | '/_app/production/'
    | '/_app/properties/'
    | '/_app/recipes/'
    | '/_app/reconciliation/'
    | '/_app/reports/'
    | '/_app/returns/'
    | '/_app/staff-meals/'
    | '/_app/staff-menu/'
    | '/_app/transfers/'
    | '/_app/users/'
    | '/_app/waste/'
    | '/_app/stock/batches/$id'
    | '/_app/store/dispatch/$orderId'
    | '/_app/stock/batches/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  PrintBillIdRoute: typeof PrintBillIdRoute
  PrintSlipIdRoute: typeof PrintSlipIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/bar-approvals': {
      id: '/_app/bar-approvals'
      path: '/bar-approvals'
      fullPath: '/bar-approvals'
      preLoaderRoute: typeof AppBarApprovalsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/float': {
      id: '/_app/float'
      path: '/float'
      fullPath: '/float'
      preLoaderRoute: typeof AppFloatRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/handover': {
      id: '/_app/handover'
      path: '/handover'
      fullPath: '/handover'
      preLoaderRoute: typeof AppHandoverRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/stock': {
      id: '/_app/stock'
      path: '/stock'
      fullPath: '/stock'
      preLoaderRoute: typeof AppStockRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/store': {
      id: '/_app/store'
      path: '/store'
      fullPath: '/store'
      preLoaderRoute: typeof AppStoreRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/variance-thresholds': {
      id: '/_app/variance-thresholds'
      path: '/variance-thresholds'
      fullPath: '/variance-thresholds'
      preLoaderRoute: typeof AppVarianceThresholdsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/adjustments/': {
      id: '/_app/adjustments/'
      path: '/adjustments'
      fullPath: '/adjustments/'
      preLoaderRoute: typeof AppAdjustmentsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/adjustments/$id': {
      id: '/_app/adjustments/$id'
      path: '/adjustments/$id'
      fullPath: '/adjustments/$id'
      preLoaderRoute: typeof AppAdjustmentsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/audit/': {
      id: '/_app/audit/'
      path: '/audit'
      fullPath: '/audit/'
      preLoaderRoute: typeof AppAuditIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/audit/$id': {
      id: '/_app/audit/$id'
      path: '/audit/$id'
      fullPath: '/audit/$id'
      preLoaderRoute: typeof AppAuditIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/bar/': {
      id: '/_app/bar/'
      path: '/bar'
      fullPath: '/bar/'
      preLoaderRoute: typeof AppBarIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/bar/handover': {
      id: '/_app/bar/handover'
      path: '/bar/handover'
      fullPath: '/bar/handover'
      preLoaderRoute: typeof AppBarHandoverRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/bar/orders': {
      id: '/_app/bar/orders'
      path: '/bar/orders'
      fullPath: '/bar/orders'
      preLoaderRoute: typeof AppBarOrdersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/bar/reports': {
      id: '/_app/bar/reports'
      path: '/bar/reports'
      fullPath: '/bar/reports'
      preLoaderRoute: typeof AppBarReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/bar/stock': {
      id: '/_app/bar/stock'
      path: '/bar/stock'
      fullPath: '/bar/stock'
      preLoaderRoute: typeof AppBarStockRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/bills/': {
      id: '/_app/bills/'
      path: '/bills'
      fullPath: '/bills/'
      preLoaderRoute: typeof AppBillsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/bills/$id': {
      id: '/_app/bills/$id'
      path: '/bills/$id'
      fullPath: '/bills/$id'
      preLoaderRoute: typeof AppBillsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/cash-drops/': {
      id: '/_app/cash-drops/'
      path: '/cash-drops'
      fullPath: '/cash-drops/'
      preLoaderRoute: typeof AppCashDropsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/cash-drops/$id': {
      id: '/_app/cash-drops/$id'
      path: '/cash-drops/$id'
      fullPath: '/cash-drops/$id'
      preLoaderRoute: typeof AppCashDropsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/disputes/': {
      id: '/_app/disputes/'
      path: '/disputes'
      fullPath: '/disputes/'
      preLoaderRoute: typeof AppDisputesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/disputes/$id': {
      id: '/_app/disputes/$id'
      path: '/disputes/$id'
      fullPath: '/disputes/$id'
      preLoaderRoute: typeof AppDisputesIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/exceptions/': {
      id: '/_app/exceptions/'
      path: '/exceptions'
      fullPath: '/exceptions/'
      preLoaderRoute: typeof AppExceptionsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/exceptions/$id': {
      id: '/_app/exceptions/$id'
      path: '/exceptions/$id'
      fullPath: '/exceptions/$id'
      preLoaderRoute: typeof AppExceptionsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/menu/': {
      id: '/_app/menu/'
      path: '/menu'
      fullPath: '/menu/'
      preLoaderRoute: typeof AppMenuIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/menu/master-items': {
      id: '/_app/menu/master-items'
      path: '/menu/master-items'
      fullPath: '/menu/master-items'
      preLoaderRoute: typeof AppMenuMasterItemsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/orders/': {
      id: '/_app/orders/'
      path: '/orders'
      fullPath: '/orders/'
      preLoaderRoute: typeof AppOrdersIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/orders/$id': {
      id: '/_app/orders/$id'
      path: '/orders/$id'
      fullPath: '/orders/$id'
      preLoaderRoute: typeof AppOrdersIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/orders/new': {
      id: '/_app/orders/new'
      path: '/orders/new'
      fullPath: '/orders/new'
      preLoaderRoute: typeof AppOrdersNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/payments/': {
      id: '/_app/payments/'
      path: '/payments'
      fullPath: '/payments/'
      preLoaderRoute: typeof AppPaymentsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/payments/$id': {
      id: '/_app/payments/$id'
      path: '/payments/$id'
      fullPath: '/payments/$id'
      preLoaderRoute: typeof AppPaymentsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/payments/pending': {
      id: '/_app/payments/pending'
      path: '/payments/pending'
      fullPath: '/payments/pending'
      preLoaderRoute: typeof AppPaymentsPendingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/portion-definitions/': {
      id: '/_app/portion-definitions/'
      path: '/portion-definitions'
      fullPath: '/portion-definitions/'
      preLoaderRoute: typeof AppPortionDefinitionsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/production/': {
      id: '/_app/production/'
      path: '/production'
      fullPath: '/production/'
      preLoaderRoute: typeof AppProductionIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/production/$id': {
      id: '/_app/production/$id'
      path: '/production/$id'
      fullPath: '/production/$id'
      preLoaderRoute: typeof AppProductionIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/production/variances': {
      id: '/_app/production/variances'
      path: '/production/variances'
      fullPath: '/production/variances'
      preLoaderRoute: typeof AppProductionVariancesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/properties/': {
      id: '/_app/properties/'
      path: '/properties'
      fullPath: '/properties/'
      preLoaderRoute: typeof AppPropertiesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/recipes/': {
      id: '/_app/recipes/'
      path: '/recipes'
      fullPath: '/recipes/'
      preLoaderRoute: typeof AppRecipesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reconciliation/': {
      id: '/_app/reconciliation/'
      path: '/reconciliation'
      fullPath: '/reconciliation/'
      preLoaderRoute: typeof AppReconciliationIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reconciliation/$id': {
      id: '/_app/reconciliation/$id'
      path: '/reconciliation/$id'
      fullPath: '/reconciliation/$id'
      preLoaderRoute: typeof AppReconciliationIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports/': {
      id: '/_app/reports/'
      path: '/reports'
      fullPath: '/reports/'
      preLoaderRoute: typeof AppReportsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/returns/': {
      id: '/_app/returns/'
      path: '/returns'
      fullPath: '/returns/'
      preLoaderRoute: typeof AppReturnsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/returns/$id': {
      id: '/_app/returns/$id'
      path: '/returns/$id'
      fullPath: '/returns/$id'
      preLoaderRoute: typeof AppReturnsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/staff-meals/': {
      id: '/_app/staff-meals/'
      path: '/staff-meals'
      fullPath: '/staff-meals/'
      preLoaderRoute: typeof AppStaffMealsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/staff-meals/$id': {
      id: '/_app/staff-meals/$id'
      path: '/staff-meals/$id'
      fullPath: '/staff-meals/$id'
      preLoaderRoute: typeof AppStaffMealsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/staff-meals/daily': {
      id: '/_app/staff-meals/daily'
      path: '/staff-meals/daily'
      fullPath: '/staff-meals/daily'
      preLoaderRoute: typeof AppStaffMealsDailyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/staff-menu/': {
      id: '/_app/staff-menu/'
      path: '/staff-menu'
      fullPath: '/staff-menu/'
      preLoaderRoute: typeof AppStaffMenuIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/staff-menu/$weekStart': {
      id: '/_app/staff-menu/$weekStart'
      path: '/staff-menu/$weekStart'
      fullPath: '/staff-menu/$weekStart'
      preLoaderRoute: typeof AppStaffMenuWeekStartRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/staff-menu/standing': {
      id: '/_app/staff-menu/standing'
      path: '/staff-menu/standing'
      fullPath: '/staff-menu/standing'
      preLoaderRoute: typeof AppStaffMenuStandingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/stock/balance': {
      id: '/_app/stock/balance'
      path: '/balance'
      fullPath: '/stock/balance'
      preLoaderRoute: typeof AppStockBalanceRouteImport
      parentRoute: typeof AppStockRoute
    }
    '/_app/stock/batches': {
      id: '/_app/stock/batches'
      path: '/batches'
      fullPath: '/stock/batches'
      preLoaderRoute: typeof AppStockBatchesRouteImport
      parentRoute: typeof AppStockRoute
    }
    '/_app/stock/bulk-issues': {
      id: '/_app/stock/bulk-issues'
      path: '/bulk-issues'
      fullPath: '/stock/bulk-issues'
      preLoaderRoute: typeof AppStockBulkIssuesRouteImport
      parentRoute: typeof AppStockRoute
    }
    '/_app/stock/items': {
      id: '/_app/stock/items'
      path: '/items'
      fullPath: '/stock/items'
      preLoaderRoute: typeof AppStockItemsRouteImport
      parentRoute: typeof AppStockRoute
    }
    '/_app/stock/ledger': {
      id: '/_app/stock/ledger'
      path: '/ledger'
      fullPath: '/stock/ledger'
      preLoaderRoute: typeof AppStockLedgerRouteImport
      parentRoute: typeof AppStockRoute
    }
    '/_app/stock/portion': {
      id: '/_app/stock/portion'
      path: '/portion'
      fullPath: '/stock/portion'
      preLoaderRoute: typeof AppStockPortionRouteImport
      parentRoute: typeof AppStockRoute
    }
    '/_app/stock/portion-inventory': {
      id: '/_app/stock/portion-inventory'
      path: '/portion-inventory'
      fullPath: '/stock/portion-inventory'
      preLoaderRoute: typeof AppStockPortionInventoryRouteImport
      parentRoute: typeof AppStockRoute
    }
    '/_app/store/queue': {
      id: '/_app/store/queue'
      path: '/queue'
      fullPath: '/store/queue'
      preLoaderRoute: typeof AppStoreQueueRouteImport
      parentRoute: typeof AppStoreRoute
    }
    '/_app/store/slips': {
      id: '/_app/store/slips'
      path: '/slips'
      fullPath: '/store/slips'
      preLoaderRoute: typeof AppStoreSlipsRouteImport
      parentRoute: typeof AppStoreRoute
    }
    '/_app/transfers/': {
      id: '/_app/transfers/'
      path: '/transfers'
      fullPath: '/transfers/'
      preLoaderRoute: typeof AppTransfersIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/transfers/$id': {
      id: '/_app/transfers/$id'
      path: '/transfers/$id'
      fullPath: '/transfers/$id'
      preLoaderRoute: typeof AppTransfersIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/users/': {
      id: '/_app/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof AppUsersIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/waste/': {
      id: '/_app/waste/'
      path: '/waste'
      fullPath: '/waste/'
      preLoaderRoute: typeof AppWasteIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/waste/$id': {
      id: '/_app/waste/$id'
      path: '/waste/$id'
      fullPath: '/waste/$id'
      preLoaderRoute: typeof AppWasteIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_print/bill/$id': {
      id: '/_print/bill/$id'
      path: '/bill/$id'
      fullPath: '/bill/$id'
      preLoaderRoute: typeof PrintBillIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_print/slip/$id': {
      id: '/_print/slip/$id'
      path: '/slip/$id'
      fullPath: '/slip/$id'
      preLoaderRoute: typeof PrintSlipIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/stock/batches/': {
      id: '/_app/stock/batches/'
      path: '/'
      fullPath: '/stock/batches/'
      preLoaderRoute: typeof AppStockBatchesIndexRouteImport
      parentRoute: typeof AppStockBatchesRoute
    }
    '/_app/stock/batches/$id': {
      id: '/_app/stock/batches/$id'
      path: '/$id'
      fullPath: '/stock/batches/$id'
      preLoaderRoute: typeof AppStockBatchesIdRouteImport
      parentRoute: typeof AppStockBatchesRoute
    }
    '/_app/store/dispatch/$orderId': {
      id: '/_app/store/dispatch/$orderId'
      path: '/dispatch/$orderId'
      fullPath: '/store/dispatch/$orderId'
      preLoaderRoute: typeof AppStoreDispatchOrderIdRouteImport
      parentRoute: typeof AppStoreRoute
    }
  }
}

interface AppStockBatchesRouteChildren {
  AppStockBatchesIdRoute: typeof AppStockBatchesIdRoute
  AppStockBatchesIndexRoute: typeof AppStockBatchesIndexRoute
}

const AppStockBatchesRouteChildren: AppStockBatchesRouteChildren = {
  AppStockBatchesIdRoute: AppStockBatchesIdRoute,
  AppStockBatchesIndexRoute: AppStockBatchesIndexRoute,
}

const AppStockBatchesRouteWithChildren = AppStockBatchesRoute._addFileChildren(
  AppStockBatchesRouteChildren,
)

interface AppStockRouteChildren {
  AppStockBalanceRoute: typeof AppStockBalanceRoute
  AppStockBatchesRoute: typeof AppStockBatchesRouteWithChildren
  AppStockBulkIssuesRoute: typeof AppStockBulkIssuesRoute
  AppStockItemsRoute: typeof AppStockItemsRoute
  AppStockLedgerRoute: typeof AppStockLedgerRoute
  AppStockPortionRoute: typeof AppStockPortionRoute
  AppStockPortionInventoryRoute: typeof AppStockPortionInventoryRoute
}

const AppStockRouteChildren: AppStockRouteChildren = {
  AppStockBalanceRoute: AppStockBalanceRoute,
  AppStockBatchesRoute: AppStockBatchesRouteWithChildren,
  AppStockBulkIssuesRoute: AppStockBulkIssuesRoute,
  AppStockItemsRoute: AppStockItemsRoute,
  AppStockLedgerRoute: AppStockLedgerRoute,
  AppStockPortionRoute: AppStockPortionRoute,
  AppStockPortionInventoryRoute: AppStockPortionInventoryRoute,
}

const AppStockRouteWithChildren = AppStockRoute._addFileChildren(
  AppStockRouteChildren,
)

interface AppStoreRouteChildren {
  AppStoreQueueRoute: typeof AppStoreQueueRoute
  AppStoreSlipsRoute: typeof AppStoreSlipsRoute
  AppStoreDispatchOrderIdRoute: typeof AppStoreDispatchOrderIdRoute
}

const AppStoreRouteChildren: AppStoreRouteChildren = {
  AppStoreQueueRoute: AppStoreQueueRoute,
  AppStoreSlipsRoute: AppStoreSlipsRoute,
  AppStoreDispatchOrderIdRoute: AppStoreDispatchOrderIdRoute,
}

const AppStoreRouteWithChildren = AppStoreRoute._addFileChildren(
  AppStoreRouteChildren,
)

interface AppRouteChildren {
  AppBarApprovalsRoute: typeof AppBarApprovalsRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppFloatRoute: typeof AppFloatRoute
  AppHandoverRoute: typeof AppHandoverRoute
  AppStockRoute: typeof AppStockRouteWithChildren
  AppStoreRoute: typeof AppStoreRouteWithChildren
  AppVarianceThresholdsRoute: typeof AppVarianceThresholdsRoute
  AppAdjustmentsIdRoute: typeof AppAdjustmentsIdRoute
  AppAuditIdRoute: typeof AppAuditIdRoute
  AppBarHandoverRoute: typeof AppBarHandoverRoute
  AppBarOrdersRoute: typeof AppBarOrdersRoute
  AppBarReportsRoute: typeof AppBarReportsRoute
  AppBarStockRoute: typeof AppBarStockRoute
  AppBillsIdRoute: typeof AppBillsIdRoute
  AppCashDropsIdRoute: typeof AppCashDropsIdRoute
  AppDisputesIdRoute: typeof AppDisputesIdRoute
  AppExceptionsIdRoute: typeof AppExceptionsIdRoute
  AppMenuMasterItemsRoute: typeof AppMenuMasterItemsRoute
  AppOrdersIdRoute: typeof AppOrdersIdRoute
  AppOrdersNewRoute: typeof AppOrdersNewRoute
  AppPaymentsIdRoute: typeof AppPaymentsIdRoute
  AppPaymentsPendingRoute: typeof AppPaymentsPendingRoute
  AppProductionIdRoute: typeof AppProductionIdRoute
  AppProductionVariancesRoute: typeof AppProductionVariancesRoute
  AppReconciliationIdRoute: typeof AppReconciliationIdRoute
  AppReturnsIdRoute: typeof AppReturnsIdRoute
  AppStaffMealsIdRoute: typeof AppStaffMealsIdRoute
  AppStaffMealsDailyRoute: typeof AppStaffMealsDailyRoute
  AppStaffMenuWeekStartRoute: typeof AppStaffMenuWeekStartRoute
  AppStaffMenuStandingRoute: typeof AppStaffMenuStandingRoute
  AppTransfersIdRoute: typeof AppTransfersIdRoute
  AppWasteIdRoute: typeof AppWasteIdRoute
  AppAdjustmentsIndexRoute: typeof AppAdjustmentsIndexRoute
  AppAuditIndexRoute: typeof AppAuditIndexRoute
  AppBarIndexRoute: typeof AppBarIndexRoute
  AppBillsIndexRoute: typeof AppBillsIndexRoute
  AppCashDropsIndexRoute: typeof AppCashDropsIndexRoute
  AppDisputesIndexRoute: typeof AppDisputesIndexRoute
  AppExceptionsIndexRoute: typeof AppExceptionsIndexRoute
  AppMenuIndexRoute: typeof AppMenuIndexRoute
  AppOrdersIndexRoute: typeof AppOrdersIndexRoute
  AppPaymentsIndexRoute: typeof AppPaymentsIndexRoute
  AppPortionDefinitionsIndexRoute: typeof AppPortionDefinitionsIndexRoute
  AppProductionIndexRoute: typeof AppProductionIndexRoute
  AppPropertiesIndexRoute: typeof AppPropertiesIndexRoute
  AppRecipesIndexRoute: typeof AppRecipesIndexRoute
  AppReconciliationIndexRoute: typeof AppReconciliationIndexRoute
  AppReportsIndexRoute: typeof AppReportsIndexRoute
  AppReturnsIndexRoute: typeof AppReturnsIndexRoute
  AppStaffMealsIndexRoute: typeof AppStaffMealsIndexRoute
  AppStaffMenuIndexRoute: typeof AppStaffMenuIndexRoute
  AppTransfersIndexRoute: typeof AppTransfersIndexRoute
  AppUsersIndexRoute: typeof AppUsersIndexRoute
  AppWasteIndexRoute: typeof AppWasteIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppBarApprovalsRoute: AppBarApprovalsRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppFloatRoute: AppFloatRoute,
  AppHandoverRoute: AppHandoverRoute,
  AppStockRoute: AppStockRouteWithChildren,
  AppStoreRoute: AppStoreRouteWithChildren,
  AppVarianceThresholdsRoute: AppVarianceThresholdsRoute,
  AppAdjustmentsIdRoute: AppAdjustmentsIdRoute,
  AppAuditIdRoute: AppAuditIdRoute,
  AppBarHandoverRoute: AppBarHandoverRoute,
  AppBarOrdersRoute: AppBarOrdersRoute,
  AppBarReportsRoute: AppBarReportsRoute,
  AppBarStockRoute: AppBarStockRoute,
  AppBillsIdRoute: AppBillsIdRoute,
  AppCashDropsIdRoute: AppCashDropsIdRoute,
  AppDisputesIdRoute: AppDisputesIdRoute,
  AppExceptionsIdRoute: AppExceptionsIdRoute,
  AppMenuMasterItemsRoute: AppMenuMasterItemsRoute,
  AppOrdersIdRoute: AppOrdersIdRoute,
  AppOrdersNewRoute: AppOrdersNewRoute,
  AppPaymentsIdRoute: AppPaymentsIdRoute,
  AppPaymentsPendingRoute: AppPaymentsPendingRoute,
  AppProductionIdRoute: AppProductionIdRoute,
  AppProductionVariancesRoute: AppProductionVariancesRoute,
  AppReconciliationIdRoute: AppReconciliationIdRoute,
  AppReturnsIdRoute: AppReturnsIdRoute,
  AppStaffMealsIdRoute: AppStaffMealsIdRoute,
  AppStaffMealsDailyRoute: AppStaffMealsDailyRoute,
  AppStaffMenuWeekStartRoute: AppStaffMenuWeekStartRoute,
  AppStaffMenuStandingRoute: AppStaffMenuStandingRoute,
  AppTransfersIdRoute: AppTransfersIdRoute,
  AppWasteIdRoute: AppWasteIdRoute,
  AppAdjustmentsIndexRoute: AppAdjustmentsIndexRoute,
  AppAuditIndexRoute: AppAuditIndexRoute,
  AppBarIndexRoute: AppBarIndexRoute,
  AppBillsIndexRoute: AppBillsIndexRoute,
  AppCashDropsIndexRoute: AppCashDropsIndexRoute,
  AppDisputesIndexRoute: AppDisputesIndexRoute,
  AppExceptionsIndexRoute: AppExceptionsIndexRoute,
  AppMenuIndexRoute: AppMenuIndexRoute,
  AppOrdersIndexRoute: AppOrdersIndexRoute,
  AppPaymentsIndexRoute: AppPaymentsIndexRoute,
  AppPortionDefinitionsIndexRoute: AppPortionDefinitionsIndexRoute,
  AppProductionIndexRoute: AppProductionIndexRoute,
  AppPropertiesIndexRoute: AppPropertiesIndexRoute,
  AppRecipesIndexRoute: AppRecipesIndexRoute,
  AppReconciliationIndexRoute: AppReconciliationIndexRoute,
  AppReportsIndexRoute: AppReportsIndexRoute,
  AppReturnsIndexRoute: AppReturnsIndexRoute,
  AppStaffMealsIndexRoute: AppStaffMealsIndexRoute,
  AppStaffMenuIndexRoute: AppStaffMenuIndexRoute,
  AppTransfersIndexRoute: AppTransfersIndexRoute,
  AppUsersIndexRoute: AppUsersIndexRoute,
  AppWasteIndexRoute: AppWasteIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  PrintBillIdRoute: PrintBillIdRoute,
  PrintSlipIdRoute: PrintSlipIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
